spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.database=${SPRING_DATA_REDIS_DATABASE:0}
spring.data.redis.timeout=${SPRING_DATA_REDIS_TIMEOUT:10s}

mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.nologging.NoLoggingImpl
